### ISSUE TITLE
Ligatures for coding support in Fairfax HD?

### ISSUE THREAD

**Issue by bartvdo** [kreativekorp/open-relay#1]
Hi, 

This is a great font! Thanks for your work!
One thing that I'd like to know is whether you are going to add Ligatures (for example like those in https://github.com/tonsky/FiraCode) ?

**Comment by RebeccaRGB** [comment]
Even though I personally believe programming ligatures shouldn't be a thing, there is now a version of Fairfax HD that has them. It's called Fairfax Hax HD and can be downloaded from the [FairfaxHD](https://github.com/kreativekorp/open-relay/tree/master/FairfaxHD) directory alongside the non-ligatured version.
