### ISSUE TITLE
YOUR PRIVATE USE WILL APPEAR IN COMPETITOR FONTS

### ISSUE THREAD

**Issue by Audowlxkjdjw** [kreativekorp/open-relay#19]
NO CREDIT TO YOU

**Comment by Audowlxkjdjw** [comment]
It will be absolutely terrifying, You'll see hex byte pictures, and also fill patterns, and block sethants and octants, also shade quarters. You'll also see legacy computing characters, and superscripts/subscripts/smallcapitals (will be extended as well) and inverted characters (will be extended as well).

**Comment by Audowlxkjdjw** [comment]
You'll also see the non-standard punctuation, and the custom Greek letters, and seven segment display patterns. You'll be starting to regret the decision not to self-promote, and immediately start making an advertisement.

**Comment by RebeccaRGB** [comment]
If my Private Use characters start appearing in other fonts, with or without credit, I will be overjoyed. No regrets whatsoever. That is in the spirit of open-source software, something of which you obviously lack a basic understanding.
