### ISSUE TITLE
There is a competitor

### ISSUE THREAD

**Issue by 289aincwaeubr** [kreativekorp/open-relay#2]
I would like to inform, that Fairfax has a competitor named Custom Font ttf. Custom Font ttf currently offers 6×12 and 8×16 versions, and three character set versions (1.0 with 678 characters, 2.0 with 1193 characters, 3.0 with 3309 characters). In Custom Font ttf, no glyph ever has a different width than given or exceeds the given bounding box. https://typedesign.netlify.com/customfont.html

**Comment by RebeccaRGB** [comment]
No advertising please.

**Comment by PiotrGrochowski** [comment]
There was a mistake. Custom Font ttf 3.0 has 2823 characters, not 3309.
