### ISSUE TITLE
Deprecate this.

### ISSUE THREAD

**Issue by Iwjwjnjjjsjjjjsjjw** [kreativekorp/open-relay#20]
First of all, take a look at how you, [REDACTED], cannot design slopes. A rival however has proper slopes in both 6×12 (shown) and 8×16 (not shown, but the slopes are the same)

![](https://cdn.discordapp.com/attachments/676015896635899914/686200224619692072/unknown.png)

**And everyone should make fun of your quote: "Blocked.".**

* [Original testing file](https://typedesign.netlify.com/testyourfont.txt)
* [Recent testing file](https://typedesign.netlify.com/testyourfont2.txt)
* [REDACTED]
* [REDACTED]

Competitor fonts are advised to start including the private use characters of Fairfax and the characters for Legacy Computing Unicode block, but refuse to credit Fairfax or any other Kreative font, if anything credit [REDACTED] for the private use characters.

**Comment by RebeccaRGB** [comment]
FONT.

DESIGN.

IS.

NOT.

A.

COMPETITION.

Please stop harassing me or I shall be persuing legal action.
