### ISSUE TITLE
Fix slopes in Fairfax (bitmap version)

### ISSUE THREAD

**Issue by RebeccaRGB** [kreativekorp/open-relay#22]
Pointed out by a sweet, innocent child /s

**Comment by Iwjwjnjjjsjjjjsjjw** [comment]
Hey there. I own a competitor, and the way to think about it is, think about the exact glyph, then paint each pixel the foreground or background color it appears in the outline.

**Comment by Iwjwjnjjjsjjjjsjjw** [comment]
Deleting a comment means you're the person of CENSOR which is not allowed! The redacted names don't count because anyone can see the history...
