### ISSUE TITLE
Whether a pixel of a slope character is a foreground color or a background color is determined by the center of a pixel of the exact outline. What part of it do you not understand?

### ISSUE THREAD

**Issue by Iwjwjnjjjsjjjjsjjw-Plus** [kreativekorp/open-relay#24]
# Whether a pixel of a slope character is a foreground color or a background color is determined by the center of a pixel of the exact outline. What part of it do you not understand?

**Comment by RebeccaRGB** [comment]
I understand that perfectly. The issue is that you keep posting that while advertising your own font instead and have been harassing me for the past three weeks.
