### ISSUE TITLE
What is Fairfax' discord server?

### ISSUE THREAD

**Issue by Iwjwjnjjjsjjjjsjjw-Plus** [kreativekorp/open-relay#25]
Any good freefont must have a Discord server. For example, in case of DMCA Sans Serif (in fact all the fonts on Type Design) it is https://discord.gg/Vh779u9 .

If you see [REDACTED] above, click on the 'edited' text and select the version before Kreative's edit.

**Comment by RebeccaRGB** [comment]
I do not have a Discord server. And if I did, I would not share it with a man who has been harassing me for the past three weeks.
