### ISSUE TITLE
Whether a pixel of a slope character is a foreground color or a background color is determined by the center of a pixel of the exact outline. What part of it do you not understand?

### ISSUE THREAD

**Issue by Rikakmnhhdio** [kreativekorp/open-relay#27]
I've been studying bitmap fonts at one of the highest rated universities and sororities (you know, with fake Greek) and this is the very first thing they taught me!

## Whether a pixel of a slope character is a foreground color or a background color is determined by the center of a pixel of the exact outline. What part of it do you not understand?

**Comment by RebeccaRGB** [comment]
I understand it perfectly. The issue is that you keep posting that while advertising your own font and harassing me.
