### ISSUE TITLE
Make an advertisement

### ISSUE THREAD

**Issue by PiotrGrochowski** [kreativekorp/open-relay#4]
In typedesign.netlify.com/fonts.html

This is a critical issue. A failure to self-promote your font demonstrates that you can't demonstrate how your font is a good (and I don't just mean decent) competitor of its competitors. If you don't successfully make an advertisement, Type Design will start discouraging the use of your font in public.

If you can make an advertisement but it would take a lot of time, let me know. In this case, after the advertisement gets done, the font will be self-promoted on the website and no longer blacklisted.

**Comment by RebeccaRGB** [comment]
Blocked.
