### ISSUE TITLE
Wrong glyph for U+1D10 LATIN LETTER SMALL CAPITAL OPEN O in Fairfax HD

### ISSUE THREAD

**Issue by dscorbett** [kreativekorp/open-relay#58]
In Fairfax HD, U+1D10 LATIN LETTER SMALL CAPITAL OPEN O looks identical to U+0254 LATIN SMALL LETTER OPEN O, instead of like a small capital U+0186 LATIN CAPITAL LETTER OPEN O. Here is <U+0186, U+0254, U+1D10>:
![Ɔɔᴐ](https://user-images.githubusercontent.com/1124347/96898012-3645f300-145d-11eb-8c5f-28bc9aaaa87c.png)
Compare <U+0043, U+0063, U+1D04>:
![Ccᴄ](https://user-images.githubusercontent.com/1124347/96898339-9b014d80-145d-11eb-89a8-3c4bf6bea514.png)

**Comment by RebeccaRGB** [comment]
This will be fixed in the next release.
