### ISSUE TITLE
Great news regarding all the Herman Miller scripts in the CSUR!

### ISSUE THREAD

**Issue by MBear227** [kreativekorp/open-relay#60]
I have an archive of a page with almost all of the scripts:

http://web.archive.org/web/20171210193150/https://www.prismnet.com/~hmiller/lang/KolagianWriting.html

(The page is still up unarchived, but not the images. That archive should have all the images.)

Just thought I'd show you this, you can now add them to Fairfax HD and others if you want.

**Comment by RebeccaRGB** [comment]
Thanks! I also found the same archive. That's how I was able to add Saklor and Kelwathi. The others will be added over time.

**Comment by RebeccaRGB** [comment]
All the Herman Miller scripts have been included in Fairfax and Fairfax HD for a while now, so closing this.
