### ISSUE TITLE
Request: P8SCII Characters 0x7F-0x99 

### ISSUE THREAD

**Issue by oshaboy** [kreativekorp/open-relay#68]
I attached a picture of the characters in question. These are used in the Fantasy computer Pico8.
![image](https://user-images.githubusercontent.com/35503208/212494923-c73f56e3-75f6-4ec8-9c1a-afd559759126.png)

Some of these are already in the font, but characters like "Jelpi", "Throwing Star" and all of the buttons don't really have proper equivalents. So.. let me propose.

```
0xffc27 => Jelpi
0xffc28 => Pico 8 Down Key
0xffc29 => Scattered Dots
0xffc2a => Throwing Star
0xffc2b => Ball
0xffc2c => Eye
0xffc2d => Man
0xffc2e => House
0xffc2f => Pico8 Left Key
0xffc37 => Face
0xffc38 => Pico8 Circle Key
0xffc39 => Pico8 Right Key
0xffc3a => Pico8 Up Key
0xffc3b => Birds
0xffc3c => Sawtooth
0xffc3d => Pico8 Cross Key
0xffc3e => Three Horizontal Lines
0xffc3f => Three Vertical Lines
```

**Comment by oshaboy** [comment]
I see they got added to ff800 to ff80f.

**Comment by RebeccaRGB** [comment]
Why reopen this? All these characters have been added.

**Comment by oshaboy** [comment]
I think it was by mistake
