### ISSUE TITLE
Historical explanations

### ISSUE THREAD

**Issue by miiPoP** [kreativekorp/open-relay#71]
This is not an issue, just an observation.

It would be interesting to read history,  examples, and references explaining the rationale for creating some glyphs, especially in the Private Area of the font. 

For example, in FairfaxHD why are there Quarter Capitals only for the 8 letters in "VOLS NICE"  (FFC67 to FFC7E)?  

Just curious.

**Comment by RebeccaRGB** [comment]
There is some documentation here:

https://www.kreativekorp.com/miscpages/kspua.shtml

FFC67 to FFC7E in particular are from the Coleco Adam and spell out COLECOVISION.

**Comment by miiPoP** [comment]
Ahhh, makes perfect sense. Great font, thank you!
