### ISSUE TITLE
requested renames for ihatemysalf letters

### ISSUE THREAD

**Issue by MBear227** [kreativekorp/open-relay#81]
hi this is cadex twenty-four's github account (i can prove it if you like) and i saw ihatemysalf was added to your character repertoire and got so excited! however theres a few things i had in mind

firstly there are duplicates of ꟻ ꭅ Ꝯ ꝯ as that's what they're intended to be

secondly rename requests:
FF33C;IHATEMYSALF CAPITAL LETTER VOLAPUK T
FF33D;IHATEMYSALF SMALL LETTER VOLAPUK T
FF33E;IHATEMYSALF CAPITAL LETTER KUPALOV A
FF33F;IHATEMYSALF SMALL LETTER KUPALOV A
FF350;IHATEMYSALF CAPITAL LETTER COMFORTAA A
FF351;IHATEMYSALF SMALL LETTER COMFORTAA A
FF352;IHATEMYSALF LETTER PHALLIC THISENT (just "LETTER THISENT" could work too)
FF375;IHATEMYSALF LETTER SATCHAY
FF37A;IHATEMYSALF LETTER LUCAS'S TWO
FF37E;IHATEMYSALF LETTER THE HOLY

also the stacked PW and TV originate from Poliespo, and the letters from the split crossbar ie to the mirrored ie originate from the Metelko alphabet for Slovenian, idk if these will really affect anything but if you want to encode those for those alphabets instead then feel free
unsure about having precomposed letters like ST but i guess it wouldnt hurt

**Comment by oshaboy** [comment]
Can you explain the names?

**Comment by RebeccaRGB** [comment]
Hello! Thank you for the corrections and the additional info. I'll have an updated repertoire later today.

**Comment by RebeccaRGB** [comment]
Also, thank you for introducing this transparently accessible, delightfully intuitive, and very, very beautiful writing system to the world.
